version: 2
updates:
  - package-ecosystem: npm
    directory: /src
    schedule:
      interval: weekly
      timezone: Europe/Brussels
      day: tuesday
      time: "05:00"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Europe/Brussels
      day: tuesday
      time: "05:00"
