name: "Firefly iii - Pluxee"
description: "Import Pluxee transactions effortlessly into Firefly III for streamlined finance."
version: "0.2.0"
slug: "ha-addon-pluxee"
init: false
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  cron: 0 0 6,12,18 * * *
schema:
  login: str
  password: str
  url: url
  token: str
  cron: str?
  lunch: int?
  eco: int?
  gift: int?
  sportCulture: int?
  conso: int?
  after: match(^(?:\d{4}-\d{2}-\d{2})$)?
