name: "Firefly iii - Pluxee"
description: "Import Pluxee transactions effortlessly into Firefly III for streamlined finance."
version: "0.2.0"
slug: "ha-addon-pluxee"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  cron: 0 0 6,12,18 * * *
schema:
  login: str
  password: str
  url: url
  token: str
  cron: str?
  lunch: int?
  eco: int?
  gift: int?
  sportCulture: int?
  conso: int?
  after: match(^(?:\d{4}-\d{2}-\d{2})$)?
image: "ghcr.io/olibos/{arch}-ha-addon-pluxee"